import { Injectable } from '@angular/core';
import { ICard,category,availability } from '../../models/interface-card'
@Injectable({
  providedIn: 'root'
})
export class CardsService {
  private cardsList: ICard[] = [
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/b/bayonetta-3-switch/hero",
      title: "Bayonetta™ 3",
      link:'https://www.nintendo.com/store/products/bayonetta-3-switch/',
      price:0,
      category: category.switch,
      topBar: availability.age,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/x/xenoblade-chronicles-3-switch/XBC3_SpecialEdition",
      title: "Xenoblade Chronicles™ 3 Special Edition",
      link:'https://www.nintendo.com/store/products/xenoblade-chronicles-3-special-edition-switch/',
      price:0,
      category: category.switch,
      topBar: availability.TBD,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/p/pokemon-violet-switch/hero",
      title: "Pokémon Violet",
      link:'https://www.nintendo.com/store/products/pokemon-violet-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/p/pokemon-scarlet-switch/hero",
      title: "Pokémon Scarlet",
      link:'https://www.nintendo.com/store/products/pokemon-scarlet-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/dlc/switch-dlc/pokemon-violet-dlc/rom-bundle/pokemon-scarlet-and-pokemon-violet-double-pack/image",
      title: "Pokémon Scarlet and Pokémon Violet Double Pack",
      link:'https://www.nintendo.com/store/products/pokemon-scarlet-and-pokemon-violet-double-pack-switch/',
      price:119.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/s/splatoon-3-switch/hero",
      title: "Splatoon™ 3",
      link:'https://www.nintendo.com/store/products/splatoon-3-switch/',
      price:119.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/x/xenoblade-chronicles-3-switch/hero",
      title: "Xenoblade Chronicles™ 3",
      link:'https://www.nintendo.com/store/products/xenoblade-chronicles-3-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/l/live-a-live-switch/hero",
      title: "LIVE A LIVE",
      link:'https://www.nintendo.com/store/products/live-a-live-switch/',
      price:49.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/f/fire-emblem-warriors-three-hopes-switch/hero",
      title: "Fire Emblem Warriors: Three Hopes",
      link:'https://www.nintendo.com/store/products/fire-emblem-warriors-three-hopes-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/m/mario-strikers-battle-league-switch/hero",
      title: "Mario Strikers™: Battle League",
      link:'https://www.nintendo.com/store/products/mario-strikers-battle-league-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.preOrder,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/m/mario-strikers-battle-league-first-kick-switch/hero",
      title: "Mario Strikers™: Battle League First Kick",
      link:'https://www.nintendo.com/store/products/mario-strikers-battle-league-first-kick-switch/',
      price:0,
      category: category.switch,
      topBar: availability.new,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/n/nintendo-switch-sports-switch/hero",
      title: "Nintendo Switch™ Sports",
      link:'https://www.nintendo.com/store/products/star-wars-the-force-unleashed-switch/',
      price:39.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/k/kirby-and-the-forgotten-land-switch/hero",
      title: "Kirby™ and the Forgotten Land",
      link:'https://www.nintendo.com/store/products/mario-kart-8-deluxe-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.freeDemo,
      
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/s/star-wars-the-force-unleashed-switch/hero",
      title: "STAR WARS™: The Force Unleashed™",
      link: 'https://www.nintendo.com/store/products/splatoon-2-octo-expansion-70070000001541-switch/',
      price:19.99,
      category: category.switch,
      topBar: availability.new,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/m/mario-kart-8-deluxe-switch/hero",
      title: "Mario Kart™ 8 Deluxe",
      link: 'https://www.nintendo.com/store/products/crunchyroll-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.new,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/mario-kart-8-deluxe-dlc/bundles/mario-kart-8-deluxe-booster-course-pass/image",
      title: "Mario Kart™ 8 Deluxe - Booster Course Pass",
      link: 'https://www.nintendo.com/store/products/mario-kart-8-deluxe-booster-course-pass-70070000013723-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.dlc,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/bayonetta-dlc/rom-bundle/bayonetta-and-bayonetta-2-digital-bundle/image",
      title: "Bayonetta™ and Bayonetta™ 2 Digital Bundle",
      link: 'https://www.nintendo.com/store/products/bayonetta-and-bayonetta-2-digital-bundle-switch/',
      price:59.98,
      category: category.switch,
      topBar: availability.dlc,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/b/big-brain-academy-brain-vs-brain-switch/hero",
      title: "Big Brain Academy™: Brain vs. Brain",
      link: 'https://www.nintendo.com/store/products/big-brain-academy-brain-vs-brain-switch/',
      price:29.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/p/pokemon-shining-pearl-switch/hero",
      title: "Pokémon™ Shining Pearl",
      link: 'https://www.nintendo.com/store/products/pokemon-shining-pearl-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero",
      title: "Pokémon™ Brilliant Diamond",
      link: 'https://www.nintendo.com/store/products/pokemon-brilliant-diamond-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/products/games/switch/pokemon-brilliant-diamond-pokemon-shining-pearl-double-pack/switch-pokemon-brilliant-diamond-shining-pearl-2000x2000",
      title: "Pokémon™ Brilliant Diamond and Pokémon™ Shining Pearl Double Pack",
      link: 'https://www.nintendo.com/store/products/pokemon-brilliant-diamond-pokemon-shining-pearl-double-pack/',
      price:119.98,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/pokemon-shining-pearl-dlc/rom-bundle/pokemon-brilliant-diamond-and-pokemon-shining-pearl-double-pack/image",
      title: "Pokémon™ Brilliant Diamond and Pokémon™ Shining Pearl Double Pack",
      link: 'https://www.nintendo.com/store/products/pokemon-brilliant-diamond-and-pokemon-shining-pearl-double-pack-switch/',
      price:119.99,
      category: category.switch,
      topBar: availability.dlc,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/animal-crossing-new-horizons-dlc/individual/animal-crossing-new-horizons-happy-home-paradise/image",
      title: "Animal Crossing™: New Horizons - Happy Home Paradise",
      link: 'https://www.nintendo.com/store/products/animal-crossing-new-horizons-happy-home-paradise-70050000030669-switch/',
      price:24.99,
      category: category.switch,
      topBar: availability.DLC,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/fitness-boxing-2-rhythm-and-exercise-dlc/individual/fitness-boxing-2-instructor-tunes/image",
      title: "Fitness Boxing 2: Instructor Tunes",
      link: 'https://www.nintendo.com/store/products/fitness-boxing-2-instructor-tunes-switch/',
      price:4.99,
      category: category.switch,
      topBar: availability.DLC,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/m/minecraft-switch/hero",
      title: "Minecraft",
      link: 'https://www.nintendo.com/store/products/crunchyroll-switch/',
      price:29.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/s/sega-genesis-nintendo-switch-online-switch/hero",
      title: "SEGA Genesis™ – Nintendo Switch Online",
      link: 'https://www.nintendo.com/store/products/sega-genesis-nintendo-switch-online-switch/',
      price:0,
      category: category.switch,
      topBar: availability.free,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/n/nintendo-64-nintendo-switch-online-switch/hero",
      title: "Nintendo 64™ – Nintendo Switch Online  ",
      link: 'https://www.nintendo.com/store/products/nintendo-64-nintendo-switch-online-switch/',
      price:0,
      category: category.switch,
      topBar: availability.free,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/super-smash-bros-ultimate-dlc/individual/super-smash-bros-ultimate-challenger-pack-11/image",
      title: "Super Smash Bros.™ Ultimate: Challenger Pack 11",
      link: 'https://www.nintendo.com/store/products/super-smash-bros-ultimate-challenger-pack-11-switch/',
      price:5.99,
      category: category.switch,
      topBar: availability.DLC,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/m/metroid-dread-switch/hero",
      title: "Metroid™ Dread",
      link: 'https://www.nintendo.com/store/products/metroid-dread-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/w/warioware-get-it-together-switch/hero",
      title: "WarioWare™: Get It Together!",
      link: 'https://www.nintendo.com/store/products/warioware-get-it-together-switch/',
      price:49.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/t/the-legend-of-zelda-skyward-sword-hd-switch/hero",
      title: "The Legend of Zelda™: Skyward Sword HD",
      link: 'https://www.nintendo.com/store/products/the-legend-of-zelda-skyward-sword-hd-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/fitness-boxing-2-rhythm-and-exercise-dlc/individual/fitness-boxing-2-musical-journey/image",
      title: "Fitness Boxing 2: Musical Journey",
      link: 'https://www.nintendo.com/store/products/fitness-boxing-2-musical-journey-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.DLC,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/super-smash-bros-ultimate-dlc/individual/super-smash-bros-ultimate-challenger-pack-10/image",
      title: "Super Smash Bros.™ Ultimate: Challenger Pack 10",
      link: 'https://www.nintendo.com/store/products/super-smash-bros-ultimate-challenger-pack-10-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.DLC,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/m/mario-golf-super-rush-switch/hero",
      title: "Mario Golf™: Super Rush",
      link: 'https://www.nintendo.com/store/products/mario-golf-super-rush-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/g/game-builder-garage-switch/hero",
      title: "Game Builder Garage™",
      link: 'https://www.nintendo.com/store/products/game-builder-garage-switch/',
      price:29.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/d/dc-super-hero-girls-teen-power-switch/hero",
      title: "DC Super Hero Girls™: Teen Power",
      link: 'https://www.nintendo.com/store/products/dc-super-hero-girls-teen-power-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/hyrule-warriors-age-of-calamity-dlc/rom-bundle/hyrule-warriors-age-of-calamity-plus-hyrule-warriors-age-of-calamity-expansion-pass/image",
      title: "Hyrule Warriors: Age of Calamity + Hyrule Warriors: Age of Calamity Expansion Pass",
      link: 'https://www.nintendo.com/store/products/hyrule-warriors-age-of-calamity-plus-hyrule-warriors-age-of-calamity-expansion-pass-switch/',
      price:79.98,
      category: category.switch,
      topBar: availability.dlc,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/dlc/switch-dlc/hyrule-warriors-age-of-calamity-dlc/bundles/hyrule-warriors-age-of-calamity-expansion-pass/image",
      title: "Hyrule Warriors: Age of Calamity Expansion Pass",
      link: 'https://www.nintendo.com/store/products/hyrule-warriors-age-of-calamity-expansion-pass-70070000011785-switch/',
      price:19.99,
      category: category.switch,
      topBar: availability.dlc,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/m/miitopia-switch/hero",
      title: "Miitopia™",
      link: 'https://www.nintendo.com/store/products/miitopia-switch/',
      price:49.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_200/v1/ncom/en_US/games/switch/f/famicom-detective-club-the-missing-heir-switch/hero",
      title: "Famicom Detective Club™: The Missing Heir",
      link: 'https://www.nintendo.com/store/products/famicom-detective-club-the-missing-heir-switch/',
      price:34.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/t/the-elder-scrolls-v-skyrim-switch/hero",
      title: "The Elder Scrolls V: Skyrim",
      link: 'https://www.nintendo.com/store/products/crunchyroll-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/l/lego-star-wars-the-skywalker-saga-switch/hero",
      title: "LEGO® Star Wars™: The Skywalker Saga",
      link: 'https://www.nintendo.com/store/products/lego-star-wars-the-skywalker-saga-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/t/triangle-strategy-switch/hero",
      title: "TRIANGLE STRATEGY™",
      link: 'https://www.nintendo.com/store/products/triangle-strategy-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.freeDemo,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/c/crunchyroll-switch/hero",
      title: "Crunchyroll",
      link: 'https://www.nintendo.com/store/products/crunchyroll-switch/',
      price:0,
      category: category.switch,
      topBar: availability.now,
    },
  
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/p/pokemon-legends-arceus-switch/hero",
      title: "Pokémon™ Legends: Arceus",
      link: 'https://www.nintendo.com/store/products/pokemon-legends-arceus-switch/',
      price:59.99,
      category: category.switch,
      topBar: availability.now,
    },
    {
      image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_300/v1/ncom/en_US/games/switch/m/mario-party-superstars-switch/hero",
      title: "Mario Party™ Superstars",
      link: 'https://www.nintendo.com/store/products/mario-party-superstars-switch/',
      price:59.99,
      sale:20,
      category: category.switch,
      topBar: availability.now,
    },
  
  ];
  
    
getAll(): ICard[]{
  return this.cardsList
}
getNewGames():ICard[] {
  return this.cardsList.filter(card => card.topBar === availability.now)
}
getSales():ICard[] {
  return this.cardsList.filter(card => card.sale)
}
getFreeGames():ICard[]{
  return this.cardsList.filter(card => card.price <= 0)
}

  constructor() { }
}
